services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - target: 9090
        published: 9090
    volumes:
      - type: bind
        source: ./etc/prometheus
        target: /etc/prometheus

  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - target: 3000
        published: 3000
    volumes:
      - ./data/grafana:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    restart: unless-stopped
